### ISSUE TITLE
D'n'D of YouTube Video to LinkLists does not work

### ISSUE THREAD

**Issue by UlrikeHeidler** [CoreMedia/coremedia-studio-hub#15]
Example use case: Open any article and open the library addressing a YouTube Integration node. Pick a YouTube video and Drag'n'drop the video into the "Pictures and Media" or "Related Content Items" areas. The Form seems to accept the input, but the upload does not finish successfully (see attached screenshot). The same approach does work with videos from Dropbox. Seems to be a Video-With-A-Data-URL issue. I don't see much in the logs or console that's explaining the issue further.
Sometimes, I can see the shell of the new CMVideo being created, however, neither the Video-Data-URL or the Video Title are set - sometimes, the newly created video itself is okay and only the link is broken. After a reload, the Article shows the field as it was before, the connection to the new video is not made.

![image](https://user-images.githubusercontent.com/8627964/40387249-2aa377c0-5dda-11e8-9349-a0ed679a45c8.png)

**Comment by mfaust** [comment]
When content is created, we wait until the document is feeded. Unfortunately, the preferred site is always used here, instead of the site the newly created content belongs to. Also, the timeout is silent and no message is logged. I'm fixing both issues.
