### ISSUE TITLE
YouTube-Integration: Handle playlists

### ISSUE THREAD

**Issue by UlrikeHeidler** [CoreMedia/coremedia-studio-hub#19]
It would be nice to handle playlists as well. For example, I have an article and would like to add related video content to it. Instead of selecting all videos, it would be nice to D'n'D the playlist into the "Related Content" area and the system resolves all the videos appropriately. 

As a second step, it would be a potential enhancement, to store the reference to the playlist and render all videos dynamically. Meaning, I connect my article with the playlist and even though I changed the playlist on YouTube, the current line-up of videos will be rendered dynamically.

**Comment by mfaust** [comment]
Solution will look like:

![content_ll](https://raw.githubusercontent.com/CoreMedia/coremedia-studio-hub/master/documentation/images/content_ll.png)

**Comment by mfaust** [comment]
See also: https://github.com/CoreMedia/coremedia-studio-hub/blob/master/documentation/Studio-Customization.md#custom-forms
