### ISSUE TITLE
Unable to download the dependencies

### ISSUE THREAD

**Issue by manish263160** [CoreMedia/coremedia-studio-hub#26]
[WARNING] Could not transfer metadata com.coremedia.ui.toolkit:core-icons:17-SNAPSHOT/maven-metadata.xml from/to contributions (http://repository-build.coremedia.com/nexus/content/groups/contributions/): repository-build.coremedia.com
[INFO] content-services ................................... SKIPPED
[WARNING] Could not transfer metadata com.coremedia.ui.toolkit:core-icons:17-SNAPSHOT/maven-metadata.xml from/to snapshots (http://repository-build.coremedia.com/nexus/content/groups/snapshots/): repository-build.coremedia.com
[INFO] bpa-shared ......................................... SKIPPED
[WARNING] Failure to transfer com.coremedia.ui.toolkit:core-icons:17-SNAPSHOT/maven-metadata.xml from http://repository-build.coremedia.com/nexus/content/groups/contributions/ was cached in the local repository, resolution will not be reattempted until the update interval of contributions has elapsed or updates are forced. Original error: Could not transfer metadata com.coremedia.ui.toolkit:core-icons:17-SNAPSHOT/maven-metadata.xml from/to contributions (http://repository-build.coremedia.com/nexus/content/groups/contributions/): repository-build.coremedia.com
[INFO] image-transformation ............................... SKIPPED
[INFO] test-util .......................................... SKIPPED
[WARNING] Failure to transfer com.coremedia.ui.toolkit:core-icons:17-SNAPSHOT/maven-metadata.xml from http://repository-build.coremedia.com/nexus/content/groups/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of snapshots has elapsed or updates are forced. Original error: Could not transfer metadata com.coremedia.ui.toolkit:core-icons:17-SNAPSHOT/maven-metadata.xml from/to snapshots (http://repository-build.coremedia.com/nexus/content/groups/snapshots/): repository-build.coremedia.com

**Comment by mfaust** [comment]
Can you please provide more information:
Which CoreMedia/Studio Hub version are you using?
Did you include the Studio Hub with the CoreMedia extension tool?
Have you adepted the version of the connector pom.xml with the one of the blueprint-workspace?
Is there any 17-SNAPSHOT version in any of the pom.xml files?

**Comment by manish263160** [comment]
@mfaust  I am using the latest version of studio hub in the master : https://github.com/CoreMedia/coremedia-studio-hub. My coremedia version is : 1807.1
Did you include the Studio Hub with the CoreMedia extension tool? yes I did
Have you adepted the version of the connector pom.xml with the one of the blueprint-workspace? -No
Is there any 17-SNAPSHOT version in any of the pom.xml files? - Yes

**Comment by mfaust** [comment]
Where is the 17-SNAPSHOT version? There is no such version in the Studio Hub project and the CoreMedia Blueprint Workspace does not have a SNAPSHOT version.

**Comment by manish263160** [comment]
@mfaust  Its there in the file main.js :  coremediaStudioVersion = '17-SNAPSHOT';

I can see the download attempt from the repo in the logs 
 http://repository-build.coremedia.com/nexus/content/groups/contributions/

Which is not accessible from our network, that's why build is failing I guess, Is there any simplified document having the steps for integration?

Thanks in advance :)

**Comment by mfaust** [comment]
We will try to reproduce this with the latest CM-1807.1 workspace.

**Comment by manish263160** [comment]
@mfaust  I have seen the other extensions in our project I think the parent "Exdtentions" is modified according to the project , I am sharing the "extention pom" this is like 
<parent>
    <groupId>de.init.bpa</groupId>
    <artifactId>modules</artifactId>
    <version>2018.18-SNAPSHOT</version>
  </parent>
Now what should i do?

**Comment by mfaust** [comment]
Of course the groupId and version may differ from the standard blueprint workspace.
In your case you should simply change all pom.xml files of the Studio hub so that they have the same groupId and version like the rest of the workspace.

Customize the pom.xml file of the connectors folder so that is has the same format like all other extensions, especially take care of the parent section there.

**Comment by manish263160** [comment]
@mfaust I have also tried this studio with blueprint  1807.1 coremedia release(Without our custome config), It also fails during build : 
I am using step what provide in https://github.com/CoreMedia/coremedia-studio-hub. I have got the error message during build:
[INFO] connectors-lib ..................................... FAILURE [  7.916 s]
............................
...--------------------------
```

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (enforce-onerepo-rules) on project connectors-lib
: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :connectors-lib


```

**Comment by mfaust** [comment]
So here is what I did:
- download and unzip the CoreMedia 1807.1 workspace
- clone the Studio Hub
- copy the Studio Hub folder into the extensions folder
- rename the Studio Hub folder to "connectors"
- add the "connectors" module to the extensions folder pom.xml
- ensure that the connectors/pom.xml file has the same version number of like the submodules of it(it should be 1807.1-1 or -2, however there was a problem that the root pom of the Studio Hub had a different version than the submodules)
- add "connectors" to the managed-extensions.txt
- execute "java -jar tool/extensions.jar --task synchronize --extension-config-file  extension-config.properties --task-input-file managed-extensions.txt"
- check if the connector modules have been added to the pom.xml files of the extensions-config subfolders

You should be able to build the extensions folder now.
I compiled the workspace successfully with our guest internet, so no additional access was required.

**Comment by manish263160** [comment]
@mfaust where I have to execute "java -jar tool/extensions.jar --task synchronize --extension-config-file extension-config.properties --task-input-file managed-extensions.txt"

**Comment by mfaust** [comment]
On my system that would be:
C:\workspace\blueprint-workspace\workspace\workspace-configuration\extensions

If you haven't downloaded the tool, execute this before:
mvn dependency:copy -Dartifact=com.coremedia.tools.extensions:extensions:LATEST:jar:all -DlocalRepositoryDirectory=extensions-tool -Dtransitive=false -DoutputDirectory=tool -Dmdep.stripVersion=true -Dmdep.stripClassifier=true

Check also:
https://documentation.coremedia.com/cms-9/artifacts/1804/webhelp/coremedia-en/content/projectExtensions.html

**Comment by manish263160** [comment]
@mfaust I have done all above changes in blueprint now i have this error:
```

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (enforce-onerepo-rules) on project connectors-lib
: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :connectors-lib

```

**Comment by mfaust** [comment]
The log above should show which enforcer rule has failed, There should be a more detailled message.

**Comment by manish263160** [comment]
```
[INFO] osm ................................................ SUCCESS [  0.043 s]
[INFO] osm-cae ............................................ SUCCESS [  0.666 s]
[INFO] connectors ......................................... SUCCESS [  0.034 s]
[INFO] connectors-api ..................................... SUCCESS [  0.780 s]
[INFO] connectors-lib ..................................... FAILURE [  0.104 s]
[INFO] connectors-lib-canto ............................... SKIPPED
[INFO] connectors-lib-cloudinary .......................... SKIPPED
[INFO] connectors-lib-coremedia ........................... SKIPPED
[INFO] connectors-lib-coremedia-navigation ................ SKIPPED
[INFO] connectors-lib-dropbox ............................. SKIPPED
[INFO] connectors-lib-filesystem .......................... SKIPPED
[INFO] connectors-lib-youtube ............................. SKIPPED

```

and after that this message
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
[INFO] Finished at: 2018-08-08T15:36:59+05:30
[INFO] Final Memory: 356M/1259M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (enforce-onerepo-rules) on project connectors-lib
: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :connectors-lib

```

**Comment by mfaust** [comment]
I'm running out of ideas.
You can still try to skip the enforder via mvn params

-Dcoremedia.enforcer.fail=false -Denforcer.skip=true

**Comment by manish263160** [comment]
@mfaust I have tried to resolve but now got this error : 
 ```
[INFO] Final Memory: 351M/1221M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project connectors-cae: Could not resolve dependencies for project com.coremedia.blueprint.connectors:connecto
rs-cae:jar:1807.1-1: Failure to find com.coremedia.blueprint:contentbeans:jar:17-BP-SNAPSHOT in http://maven-proxy.init.de/repository/ was cache
d in the local repository, resolution will not be reattempted until the update interval of mirror.de.init has elapsed or updates are forced -> [
Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :connectors-cae

```

**Comment by mfaust** [comment]
Change the contentbeans dependency version in connectors-cae to that one of your workspace.

**Comment by manish263160** [comment]
@mfaust dependency : 
```
<dependency>
      <groupId>com.coremedia.blueprint</groupId>
      <artifactId>contentbeans</artifactId>
      <version>17-BP-SNAPSHOT</version>
    <scope>provided</scope>
    </dependency>
```
not present in core media nexus repo, what is the exact version?

**Comment by manish263160** [comment]
@mfaust There is error in this repo:
<dependency>
      <groupId>com.coremedia.blueprint</groupId>
      <artifactId>contentbeans</artifactId>
      <version>17-BP-SNAPSHOT</version>
    <scope>provided</scope>
    </dependency>

**Comment by mfaust** [comment]
As I can see your colleagues had the same issue. Please check 
https://coremedia.zendesk.com/agent/tickets/50191
about the current status. The issue will be continued there.
