### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by sushantkumargadi** [CoreMedia/coremedia-studio-hub#28]
Somehow maven is trying to download the artifacts from : http://repository-build.coremedia.com/nexus/content/groups/contributions/ , which seems to be internal coremedia repository and is not accessible via public internet. I am trying to build the **studio hub version : 1807.1-1**

We are trying to integrate it with the **CMS version : 1807.1**

Have a look on the logs below - 

[INFO] connectors-api ..................................... FAILURE [  1.226 s
[INFO] connectors-lib ..................................... SKIPPED
[INFO] connectors-lib-s3 .................................. SKIPPED
[INFO] connectors-lib-canto ............................... SKIPPED
[INFO] connectors-lib-coremedia ........................... SKIPPED
[INFO] connectors-lib-coremedia-navigation ................ SKIPPED
[INFO] connectors-lib-cloudinary .......................... SKIPPED
[INFO] connectors-lib-youtube ............................. SKIPPED
[INFO] connectors-lib-dropbox ............................. SKIPPED
[INFO] connectors-lib-filesystem .......................... SKIPPED
[INFO] connectors-lib-rss ................................. SKIPPED
[INFO] connectors-studio-lib .............................. SKIPPED
[INFO] connectors-studio .................................. SKIPPED
[INFO] connectors-cae ..................................... SKIPPED
[INFO] connectors ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.349 s
[INFO] Finished at: 2018-08-09T12:26:27+05:30
[INFO] Final Memory: 64M/516M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project connectors-api: Could not resolve dependencies for project com.coremedia.blueprint.connectors:connectors-api:jar:1807.1-1: Failed to collect dependencies at com.coremedia.cms:cap-unified-api:jar:17-SNAPSHOT: Failed to read artifact descriptor for com.coremedia.cms:cap-unified-api:jar:17-SNAPSHOT: Could not transfer artifact com.coremedia.cms:cap-unified-api:pom:17-SNAPSHOT from/to contributions (**http://repository-build.coremedia.com/nexus/content/groups/contributions/**): repository-build.coremedia.com: Unknown host repository-build.coremedia.com -> [Help 1]

**Comment by mfaust** [comment]
As I can see your colleagues had the same issue. Please check 
https://coremedia.zendesk.com/agent/tickets/50191
about the current status. The issue will be continued there.
