### ISSUE TITLE
Not able to find "ConnectorTypes.properties"

### ISSUE THREAD

**Issue by manish263160** [CoreMedia/coremedia-studio-hub#29]
@mfaust 
Hey, I have done following steps for studio hub delpoyment:
(1) changed all folder's pom.xml parent according to my project 
(2) renamed coremedia-studio-hub folder to "connectors"
 and paste it to /extentions folder
(3) entry connectors, in managed-extensions.txt and bpa-extensions.txt file as "connectors"
(4) After that, I run "mvn clean install -DskipTests" and it is successfully done.
(4) in  "<worspace>\workspace-configuration\extensions" I execute "mvn dependency:copy -Dartifact=com.coremedia.tools.extensions:extensions:LATEST:jar:all -DlocalRepositoryDirectory=extensions-tool -Dtransitive=false -DoutputDirectory=tool -Dmdep.stripVersion=true -Dmdep.stripClassifier=true
" 
 and after this I run "java -jar tool/extensions.jar --task synchronize --extension-config-file extension-config.properties --task-input-file managed-extensions.txt " and 

"java -jar tool/extensions.jar --task synchronize --extension-config-file extension-config.properties --task-input-file bpa-extensions.txt " cause In my project there is two extensions file.
and It is successfully done.
(6) But when I open studio there is no option of connector youtube and RSS all that

What I missed 
Please help me I am new core media.

**Comment by mfaust** [comment]
I see you have opened a ticket on zendesk. I close this ticket since we follow the issue there.
