### ISSUE TITLE
Unable to build on 1810.2

### ISSUE THREAD

**Issue by nicholasfechner** [CoreMedia/coremedia-studio-hub#37]
Hi,
I tried to build this in our current workspace (currently at 1810.2) using the 1810.2 branch from this repo. But ran into a Sencha Build error:

```
[ERROR]  C2008: Requirement had no matching files (com.coremedia.cms.editor.sdk.collectionview.AbstractContextMenu) -- /Users/n.fechner/Projects/XXXX/maincms/modules/studio/studio-base-app/target/app/packages/com.coremedia.blueprint__connectors-studio/com.coremedia.blueprint__connectors-studio.js:72:43167
[ERROR]  
[ERROR]  BUILD FAILED
[ERROR]  com.sencha.exceptions.ExBuild: Failed to find any files for /Users/n.fechner/Projects/XXXX/maincms/modules/studio/studio-base-app/target/app/packages/com.coremedia.blueprint__connectors-studio/com.coremedia.blueprint__connectors-studio.js::ClassRequire::com.coremedia.cms.editor.sdk.collectionview.AbstractContextMenu
[ERROR]  	at com.sencha.command.Sencha.main(Sencha.java:1
[ERROR]  47)
[ERROR]  
[ERROR]  Total time: 16 seconds
```

Here is also the logfile generated by sencha-cmd:
[sencha-error-20190305.log](https://github.com/CoreMedia/coremedia-studio-hub/files/2931845/sencha-error-20190305.log)

**Comment by NicholasFechner** [comment]
Sorry for the update. Had to remove a customer name...

**Comment by nicholasfechner** [comment]
After I replaced the missing imported symbol with the actual string ("open"), the compile worked fine.

**Comment by mfaust** [comment]
Sorry for the late reaction, I simply must have missed the notification. I close this ticket since it looks like your fixed the problem.
