### ISSUE TITLE
Image Preview broken in Production

### ISSUE THREAD

**Issue by winniae** [CoreMedia/coremedia-studio-hub#40]
Hi, we have broken Image Previews in our production environment. What I noticed is, that Preview-Data is loaded from a URL like https://studio.mycustomer.de/studio/api/connector/item/<id> while the image is loaded from https://studio.mycustomer.de/api/connector/item/<id> without the "studio" path segment!
I guess this usually works in dev environments and our production Apache is locked down to /studio which I think is correct.

My guess, since I am not very familiar with Studio is, that ConnectorItem.java should return relative paths in the methods returning the respective paths for Blobs, so instead of
return "/api/connector/item/" + id.toUri() + "/data?mode=stream";
it should be
return "api/connector/item/" + id.toUri() + "/data?mode=stream";

**Comment by mfaust** [comment]
Hi Winfried and thank's for your feedback!
That sound's right. I just applied your suggestion so that it'll be part of the next release.
