### ISSUE TITLE
Additional columns can only be added for categories

### ISSUE THREAD

**Issue by TallenceJanHendrikPopp** [CoreMedia/coremedia-studio-hub#42]
Additional columns can only be configured for connector categories. 

(ConnectorColumnsHelper:110)
`if (category) {
      var columns:Array = category.getColumns();
      for each(var c:Object in columns) {
        //...
      }
    }`

**Comment by mfaust** [comment]
Can you be more specific what the issue is? What other entity types should be supported?

**Comment by TallenceJanHendrikPopp** [comment]
Sorry, I thought it wouldn't be possible for CategoryItems to add new columns to be displayed in the studio. But this is possible without any problems. I will close the ticket.
