### ISSUE TITLE
Label for "create new content intem" action missing (1907)

### ISSUE THREAD

**Issue by sleyer** [CoreMedia/coremedia-studio-hub#43]
The context menu item for "Create New Content Item" has lost its label. It is still there, and is still clickable and works, just the text is gone. 

Analysis: CreateConnectorContentAction label points to resource bundle package that has been moved to a different package. 
Old package: "com.coremedia.blueprint.base.components.quickcreate.QuickCreate"
New package: "com.coremedia.cms.editor.sdk.quickcreate.QuickCreate"

**Comment by mfaust** [comment]
Fixed for 1907.1 and 1907.2
