### ISSUE TITLE
Correct escaping in "create markup" function (write interceptor)

### ISSUE THREAD

**Issue by HenningThiemann** [CoreMedia/coremedia-studio-hub#44]
In the write interceptor, you create a markup from a string. See [here](https://github.com/CoreMedia/coremedia-studio-hub/blob/f4cae20205beacbfccfcb6dfc4d0b032f0e50929/connectors-lib/src/main/java/com/coremedia/blueprint/connectors/content/ConnectorItemWriteInterceptor.java#L96)

This functionality is not working currently, e.g. an "&" does not get escaped properly. If for example a teaserText contains "&", it will not be imported in the studio

**Comment by mfaust** [comment]
I fixed the problem by adding

```
description = description.replaceAll("&", "&amp;");
```

A simple encoding of all entities unfortuntely doesn't work with the `MarkupFactory`, therefore I stick to the explicit replacement of the `&` entity.
